---
- hosts: all

  roles:
    - Stouts.nginx

  vars:
    jenkins_host: "cgjenkins.svc.spsdev.in"
    proxy_server_name: "cg-jenkins-proxy.spsc.io"
    jenkins_timeout: 5
    proxy_timeout: 5
    listen_port: 80
    poll_interval: 2
    nginx_servers:
    - |
      listen {{listen_port}};
      server_name {{ proxy_server_name }};
      location / { deny all; }
      location /github-webhook {
        limit_except POST {
          deny all;
        }
        proxy_pass              https://{{ jenkins_host }};
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout   150;
        proxy_send_timeout      100;
        proxy_read_timeout      100;
        proxy_buffers           4 32k;
        client_max_body_size    8m;
        client_body_buffer_size 128k;
      }

  tasks:
    - include: tasks/main.yml
